name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install huggingface-hub
        run: pip install huggingface-hub

      - name: Login to Hugging Face
        run: huggingface-cli login --token $HF_TOKEN
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://prath3yush:$HF_TOKEN@huggingface.co/spaces/prath3yush/Search_Engine_llm
          git push hf main
